<?php 
$countriesData = [
    [
        "name" => "Francie",
        "population" => "67,1 milionu",
        "currency" => "Euro (EUR)",
        "language" => "Francouzština",
        "capital" => "Paříž",
        "area" => "551 695 km²",
        "timezone" => "GMT+1",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg"
    ],
    [
        "name" => "Španělsko",
        "population" => "47,3 milionu",
        "currency" => "Euro (EUR)",
        "language" => "Španělština",
        "capital" => "Madrid",
        "area" => "505 990 km²",
        "timezone" => "GMT+1",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg"
    ],
    [
        "name" => "Spojené státy",
        "population" => "331 milionů",
        "currency" => "Dolar (USD)",
        "language" => "Angličtina",
        "capital" => "Washington, D.C.",
        "area" => "9,83 milionu km²",
        "timezone" => "GMT-4",
        "continent" => "Severní Amerika",
        "flag" => "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg"
    ],
    [
        "name" => "Česká republika",
        "population" => "10,7 milionu",
        "currency" => "Koruna (CZK)",
        "language" => "Čeština",
        "capital" => "Praha",
        "area" => "78 866 km²",
        "timezone" => "GMT+1",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg"
    ],
    [
        "name" => "Rakousko",
        "population" => "8,9 milionu",
        "currency" => "Euro (EUR)",
        "language" => "Němčina",
        "capital" => "Vídeň",
        "area" => "83 879 km²",
        "timezone" => "GMT+1",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg"
    ],
    [
        "name" => "Německo",
        "population" => "83,2 milionu",
        "currency" => "Euro (EUR)",
        "language" => "Němčina",
        "capital" => "Berlín",
        "area" => "357 022 km²",
        "timezone" => "GMT+1",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg"
    ],
    [
        "name" => "Portugalsko",
        "population" => "10,3 milionu",
        "currency" => "Euro (EUR)",
        "language" => "Portugalština",
        "capital" => "Lisabon",
        "area" => "92 090 km²",
        "timezone" => "GMT-0",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg"
    ],
    [
        "name" => "Řecko",
        "population" => "10,4 milionu",
        "currency" => "Euro (EUR)",
        "language" => "Řečtina",
        "capital" => "Athény",
        "area" => "131 957 km²",
        "timezone" => "GMT+2",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg"
    ],
    [
        "name" => "Chorvatsko",
        "population" => "4,0 milionu",
        "currency" => "Kuna (HRK)",
        "language" => "Chorvatština",
        "capital" => "Záhřeb",
        "area" => "56 594 km²",
        "timezone" => "GMT+1",
        "continent" => "Evropa",
        "flag" => "URL_of_Croatia_Flag"
    ],
    [
        "name" => "Itálie",
        "population" => "60,4 milionu",
        "currency" => "Euro (EUR)",
        "language" => "Italština",
        "capital" => "Řím",
        "area" => "301 340 km²",
        "timezone" => "GMT+1",
        "continent" => "Evropa",
        "flag" => "URL_of_Italy_Flag"
    ],
    [
        "name" => "Turecko",
        "population" => "82,0 milionu",
        "currency" => "Turecká lira (TRY)",
        "language" => "Turečtina",
        "capital" => "Ankara",
        "area" => "783 356 km²",
        "timezone" => "GMT+3",
        "continent" => "Asie/Evropa",
        "flag" => "URL_of_Turkey_Flag"
    ],
    [
        "name" => "Thajsko",
        "population" => "69,8 milionu",
        "currency" => "Baht (THB)",
        "language" => "Thajština",
        "capital" => "Bangkok",
        "area" => "513 120 km²",
        "timezone" => "GMT+7",
        "continent" => "Asie",
        "flag" => "URL_of_Thailand_Flag"
    ],
    [
        "name" => "Bulharsko",
        "population" => "7,1 milionu",
        "currency" => "Bulharský lev (BGN)",
        "language" => "Bulharština",
        "capital" => "Sofie",
        "area" => "110 994 km²",
        "timezone" => "GMT+3",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg"
    ],
    [
        "name" => "Dominikánská republika",
        "population" => "10,8 milionu",
        "currency" => "Dominikánské peso (DOP)",
        "language" => "Španělština",
        "capital" => "Santo Domingo",
        "area" => "48 671 km²",
        "timezone" => "GMT-4",
        "continent" => "Severní Amerika",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg"
    ],
    [
        "name" => "Egypt",
        "population" => "104,2 milionu",
        "currency" => "Egyptská libra (EGP)",
        "language" => "Arabština",
        "capital" => "Káhira",
        "area" => "1 010 407 km²",
        "timezone" => "GMT+2",
        "continent" => "Afrika",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg"
    ],
    [
        "name" => "Indie",
        "population" => "1,366 miliard",
        "currency" => "Indická rupie (INR)",
        "language" => "Hindština",
        "capital" => "Nové Dillí",
        "area" => "3 287 240 km²",
        "timezone" => "GMT+5",
        "continent" => "Asie",
        "flag" => "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg"
    ],
    [
        "name" => "Maďarsko",
        "population" => "9,6 milionu",
        "currency" => "Maďarský forint (HUF)",
        "language" => "Maďarština",
        "capital" => "Budapešť",
        "area" => "93 030 km²",
        "timezone" => "GMT+2",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg"
    ],
    [
        "name" => "Spojené arabské emiráty",
        "population" => "9,9 milionu",
        "currency" => "Dirham (AED)",
        "language" => "Arabština",
        "capital" => "Abú Dhabí",
        "area" => "83 600 km²",
        "timezone" => "GMT+4",
        "continent" => "Asie",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg"
    ],
    [
        "name" => "Švýcarsko",
        "population" => "8,7 milionu",
        "currency" => "Švýcarský frank (CHF)",
        "language" => "Němčina, Francouzština, Italština, Rétorománština",
        "capital" => "Bern",
        "area" => "41 290 km²",
        "timezone" => "GMT+1",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg"
    ],
    [
        "name" => "Tunisko",
        "population" => "11,7 milionu",
        "currency" => "Tuniský dinár (TND)",
        "language" => "Arabština",
        "capital" => "Tunis",
        "area" => "163 610 km²",
        "timezone" => "GMT+1",
        "continent" => "Afrika",
        "flag" => "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg"
    ],
    [
        "name" => "Velká Británie",
        "population" => "66,7 milionu",
        "currency" => "Libra šterlinků (GBP)",
        "language" => "Angličtina",
        "capital" => "Londýn",
        "area" => "242 495 km²",
        "timezone" => "GMT-0",
        "continent" => "Evropa",
        "flag" => "https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg"
    ],
];

$typeOfTour = [
    'Pohoda u moře',
    'Přírodní tour',
    'Túry po horách',
    'Večírky a party',
    'Kulturní tour',
    'Dobrodružné tour',
    'Vinařské tour',
    'Gastro tour',
    'Fotografické tour',
    'Wellness pobyty',
    'Edukativní tour',
    'Sportovní tour',
    'Dobrovolnické tour'
  ];

  $typeOfTourObjects = [
    ['value' => 'Pohoda u moře', 'label' => 'Pohoda u moře'],
    ['value' => 'Přírodní tour', 'label' => 'Přírodní tour'],
    ['value' => 'Túry po horách', 'label' => 'Túry po horách'],
    ['value' => 'Večírky a party', 'label' => 'Večírky a party'],
    ['value' => 'Kulturní tour', 'label' => 'Kulturní tour'],
    ['value' => 'Dobrodružné tour', 'label' => 'Dobrodružné tour'],
    ['value' => 'Vinařské tour', 'label' => 'Vinařské tour'],
    ['value' => 'Gastro tour', 'label' => 'Gastro tour'],
    ['value' => 'Fotografické tour', 'label' => 'Fotografické tour'],
    ['value' => 'Wellness pobyty', 'label' => 'Wellness pobyty'],
    ['value' => 'Edukativní tour', 'label' => 'Edukativní tour'],
    ['value' => 'Sportovní tour', 'label' => 'Sportovní tour'],
    ['value' => 'Dobrovolnické tour', 'label' => 'Dobrovolnické tour'],
];

// Cast each array to an object
$typeOfTourObjects = array_map(function($type) {
    return (object) $type;
}, $typeOfTourObjects);



$countryNamesObjects = [
    (object) ['value' => 'Francie', 'label' => 'Francie'],
    (object) ['value' => 'Španělsko', 'label' => 'Španělsko'],
    (object) ['value' => 'Spojené státy', 'label' => 'Spojené státy'],
    (object) ['value' => 'Čína', 'label' => 'Čína'],
    (object) ['value' => 'Itálie', 'label' => 'Itálie'],
    (object) ['value' => 'Mexiko', 'label' => 'Mexiko'],
    (object) ['value' => 'Spojené království', 'label' => 'Spojené království'],
    (object) ['value' => 'Turecko', 'label' => 'Turecko'],
    (object) ['value' => 'Německo', 'label' => 'Německo'],
    (object) ['value' => 'Thajsko', 'label' => 'Thajsko'],
    (object) ['value' => 'Rakousko', 'label' => 'Rakousko'],
    (object) ['value' => 'Řecko', 'label' => 'Řecko'],
    (object) ['value' => 'Japonsko', 'label' => 'Japonsko'],
    (object) ['value' => 'Malajsie', 'label' => 'Malajsie'],
    (object) ['value' => 'Rusko', 'label' => 'Rusko'],
    (object) ['value' => 'Portugalsko', 'label' => 'Portugalsko'],
    (object) ['value' => 'Kanada', 'label' => 'Kanada'],
    (object) ['value' => 'Saúdská Arábie', 'label' => 'Saúdská Arábie'],
    (object) ['value' => 'Jižní Korea', 'label' => 'Jižní Korea'],
    (object) ['value' => 'Austrálie', 'label' => 'Austrálie'],
    (object) ['value' => 'Nizozemsko', 'label' => 'Nizozemsko'],
    (object) ['value' => 'Egypt', 'label' => 'Egypt'],
    (object) ['value' => 'Indie', 'label' => 'Indie'],
    (object) ['value' => 'Vietnam', 'label' => 'Vietnam'],
    (object) ['value' => 'Indonésie', 'label' => 'Indonésie'],
    (object) ['value' => 'Švýcarsko', 'label' => 'Švýcarsko'],
    (object) ['value' => 'Argentina', 'label' => 'Argentina'],
    (object) ['value' => 'Švédsko', 'label' => 'Švédsko'],
    (object) ['value' => 'Polsko', 'label' => 'Polsko'],
    (object) ['value' => 'Česká republika', 'label' => 'Česká republika'],
    (object) ['value' => 'Belgie', 'label' => 'Belgie'],
    (object) ['value' => 'Norsko', 'label' => 'Norsko'],
    (object) ['value' => 'Dánsko', 'label' => 'Dánsko'],
    (object) ['value' => 'Singapur', 'label' => 'Singapur'],
    (object) ['value' => 'Finsko', 'label' => 'Finsko'],
    (object) ['value' => 'Maroko', 'label' => 'Maroko'],
    (object) ['value' => 'Brazílie', 'label' => 'Brazílie'],
    (object) ['value' => 'Spojené arabské emiráty', 'label' => 'Spojené arabské emiráty'],
    (object) ['value' => 'Irsko', 'label' => 'Irsko'],
    (object) ['value' => 'Maďarsko', 'label' => 'Maďarsko'],
    (object) ['value' => 'Izrael', 'label' => 'Izrael'],
    (object) ['value' => 'Filipíny', 'label' => 'Filipíny'],
    (object) ['value' => 'Chile', 'label' => 'Chile'],
    (object) ['value' => 'Nový Zéland', 'label' => 'Nový Zéland'],
    (object) ['value' => 'Jižní Afrika', 'label' => 'Jižní Afrika'],
    (object) ['value' => 'Peru', 'label' => 'Peru'],
    (object) ['value' => 'Rumunsko', 'label' => 'Rumunsko'],
    (object) ['value' => 'Chorvatsko', 'label' => 'Chorvatsko'],
    (object) ['value' => 'Keňa', 'label' => 'Keňa'],
    (object) ['value' => 'Srí Lanka', 'label' => 'Srí Lanka'],
    (object) ['value' => 'Írán', 'label' => 'Írán'],
    (object) ['value' => 'Kolumbie', 'label' => 'Kolumbie'],
    (object) ['value' => 'Hongkong', 'label' => 'Hongkong'],
    (object) ['value' => 'Tanzanie', 'label' => 'Tanzanie'],
    (object) ['value' => 'Ukrajina', 'label' => 'Ukrajina'],
    (object) ['value' => 'Bulharsko', 'label' => 'Bulharsko'],
    (object) ['value' => 'Srbsko', 'label' => 'Srbsko'],
    (object) ['value' => 'Katar', 'label' => 'Katar'],
    (object) ['value' => 'Lucembursko', 'label' => 'Lucembursko'],
    (object) ['value' => 'Slovensko', 'label' => 'Slovensko'],
    (object) ['value' => 'Lotyšsko', 'label' => 'Lotyšsko'],
    (object) ['value' => 'Litva', 'label' => 'Litva'],
    (object) ['value' => 'Estonsko', 'label' => 'Estonsko'],
    (object) ['value' => 'Bahrajn', 'label' => 'Bahrajn'],
    (object) ['value' => 'Kypr', 'label' => 'Kypr'],
    (object) ['value' => 'Malta', 'label' => 'Malta'],
    (object) ['value' => 'Černá Hora', 'label' => 'Černá Hora'],
    (object) ['value' => 'Omán', 'label' => 'Omán'],
    (object) ['value' => 'Panama', 'label' => 'Panama'],
    (object) ['value' => 'Arménie', 'label' => 'Arménie'],
    (object) ['value' => 'Bosna a Hercegovina', 'label' => 'Bosna a Hercegovina'],
    (object) ['value' => 'Jordánsko', 'label' => 'Jordánsko'],
    (object) ['value' => 'Gruzie', 'label' => 'Gruzie'],
    (object) ['value' => 'Albánie', 'label' => 'Albánie'],
    (object) ['value' => 'Mauricius', 'label' => 'Mauricius'],
    (object) ['value' => 'Kuvajt', 'label' => 'Kuvajt'],
    (object) ['value' => 'Libanon', 'label' => 'Libanon'],
    (object) ['value' => 'Kostarika', 'label' => 'Kostarika'],
    (object) ['value' => 'Uruguay', 'label' => 'Uruguay'],
    (object) ['value' => 'Kazachstán', 'label' => 'Kazachstán'],
    (object) ['value' => 'Bolívie', 'label' => 'Bolívie'],
    (object) ['value' => 'Guatemala', 'label' => 'Guatemala'],
    (object) ['value' => 'Ekvádor', 'label' => 'Ekvádor'],
    (object) ['value' => 'Island', 'label' => 'Island'],
    (object) ['value' => 'Makedonie', 'label' => 'Makedonie'],
    (object) ['value' => 'Nepál', 'label' => 'Nepál'],
    (object) ['value' => 'Paraguay', 'label' => 'Paraguay'],
    (object) ['value' => 'Zimbabwe', 'label' => 'Zimbabwe'],
    (object) ['value' => 'Ghana', 'label' => 'Ghana'],
    (object) ['value' => 'Ázerbájdžán', 'label' => 'Ázerbájdžán'],
    (object) ['value' => 'Zambie', 'label' => 'Zambie'],
    (object) ['value' => 'Honduras', 'label' => 'Honduras'],
    (object) ['value' => 'Jamajka', 'label' => 'Jamajka'],
    (object) ['value' => 'Etiopie', 'label' => 'Etiopie'],
    (object) ['value' => 'Kamerun', 'label' => 'Kamerun'],
    (object) ['value' => 'Madagaskar', 'label' => 'Madagaskar'],
    (object) ['value' => 'Kuba', 'label' => 'Kuba'],
];


